pagetitle: OData Vocabularies Version 4.0
subtitle: Committee Specification Draft 03
filename: odata-vocabularies-v4.0-csd03
stage: csd03
previousStage: csd02
pubdate: 19 August 2026
pubdateISO: '2026-08-19'
copyright: © OASIS Open 2026
description: >
  This prose specification describes a set of OData vocabularies maintained
  by the OASIS OData Technical Committee.
  These vocabulary components are continuously evolved.
  The latest work-in-progress revisions are available at the odata-vocabularies
  OASIS TC GitHub repository: https://github.com/oasis-tcs/odata-vocabularies.
repo: odata-vocabularies
pandocOptions:
  -F: lib/vocab2html.js
