pagetitle: OData Common Schema Definition Language (CSDL) JSON Representation Version 4.02
subtitle: Committee Specification Draft 01
filename: odata-csdl-json-v4.02-csd01
pubdate: 14 July 2023
pubdateISO: '2023-07-14'
copyright: © OASIS Open 2023
