name: OData-URL
url: https://docs.oasis-open.org/odata/odata/v4.02/odata-v4.02-part2-url-conventions.html
pagetitle: 'OData Version 4.02. Part 2: URL Conventions'
subtitle: Committee Specification Draft 02
filename: odata-v4.02-csd02-part2-url-conventions
stage: csd02
previousStage: csd01
pubdate: 28 February 2024
pubdateISO: '2024-02-28'
copyright: © OASIS Open 2024
archivename: odata-v4.02-csd02
partname: part2-url-conventions
description:
  The Open Data Protocol (OData) enables the creation of REST-based data services,
  which allow resources, identified using Uniform Resource Locators (URLs) and
  defined in an Entity Data Model (EDM), to be published and edited by Web clients
  using simple HTTP messages.
  This specification defines a set of recommended (but not required) rules for
  constructing URLs to identify the data and metadata exposed by an OData service
  as well as a set of reserved URL query string operators.
