pagetitle: 'OData Version 4.01. Part 1: Protocol'
subtitle: Committee Specification Draft 01
filename: odata-v4.02-csd01-part1-protocol
stage: csd01
previousStage: n/a
pubdate: 14 July 2023
pubdateISO: '2023-07-14'
copyright: © OASIS Open 2023
