pagetitle: 'OData Version 4.02. Part 1: Protocol'
subtitle: Committee Specification Draft 01
filename: odata-v4.02-csd01-part1-protocol
stage: csd01
previousStage: n/a
pubdate: 14 July 2023
pubdateISO: '2023-07-14'
copyright: © OASIS Open 2023
description:
  The Open Data Protocol (OData) enables the creation of REST-based data services,
  which allow resources, identified using Uniform Resource Locators (URLs) and
  defined in an Entity Data Model (EDM), to be published and edited by Web clients
  using simple HTTP messages. This document defines the core semantics and facilities of the protocol.
