name: OData-Protocol
url: https://docs.oasis-open.org/odata/odata/v4.02/odata-v4.02-part1-protocol.html
pagetitle: 'OData Version 4.02. Part 1: Protocol'
subtitle: Committee Specification Draft 02
filename: odata-v4.02-csd02-part1-protocol
stage: csd02
previousStage: csd01
pubdate: 28 February 2024
pubdateISO: '2024-02-28'
copyright: © OASIS Open 2024
archivename: odata-v4.02-csd02
partname: part1-protocol
additionalArtifacts:
  - repo: odata-abnf
    path: abnf/odata-abnf-construction-rules.txt
    branch: v4.02-release-candidate
  - repo: odata-abnf
    path: abnf/odata-abnf-testcases.yaml
    branch: v4.02-release-candidate
description:
  The Open Data Protocol (OData) enables the creation of REST-based data services,
  which allow resources, identified using Uniform Resource Locators (URLs) and
  defined in an Entity Data Model (EDM), to be published and edited by Web clients
  using simple HTTP messages. This document defines the core semantics and facilities of the protocol.
