name: OData-Data-Agg
url: https://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/odata-data-aggregation-ext-v4.0.html
pagetitle: OData Extension for Data Aggregation Version 4.0
subtitle: Committee Specification Draft 05
filename: odata-data-aggregation-ext-v4.0-csd05
stage: csd05
previousStage: cs03
pubdate: 17 September 2025
pubdateISO: '2025-09-17'
copyright: © OASIS Open 2023
additionalArtifacts:
  - repo: odata-vocabularies
    path: vocabularies/Org.OData.Aggregation.V1.json
    branch: v4.02-release-candidate
  - repo: odata-vocabularies
    path: vocabularies/Org.OData.Aggregation.V1.xml
    branch: v4.02-release-candidate
description:
  This specification adds basic grouping and aggregation functionality (e.g. sum, min, and max)
  to the Open Data Protocol (OData) without changing any of the base principles of OData.
