pagetitle: OData Extension for Data Aggregation Version 4.0
subtitle: Committee Specification Draft 04
filename: odata-data-aggregation-ext-v4.0-csd04
stage: csd04
previousStage: cs02
pubdate: 05 July 2023
pubdateISO: '2023-07-05'
copyright: © OASIS Open 2023
description:
  This specification adds basic grouping and aggregation functionality (e.g. sum, min, and max)
  to the Open Data Protocol (OData) without changing any of the base principles of OData.