pagetitle: OData Extension for Data Aggregation Version 4.0
subtitle: Committee Specification 03
filename: odata-data-aggregation-ext-v4.0-cs03
stage: cs03
previousStage: csd04
pubdate: 30 August 2023
pubdateISO: '2023-08-30'
copyright: © OASIS Open 2023
description:
  This specification adds basic grouping and aggregation functionality (e.g. sum, min, and max)
  to the Open Data Protocol (OData) without changing any of the base principles of OData.