pagetitle: OData JSON Format Version 4.02
subtitle: Committee Specification Draft 01
filename: odata-json-format-v4.02-csd01
stage: csd01
previousStage: n/a
pubdate: 14 July 2023
pubdateISO: '2023-07-14'
copyright: © OASIS Open 2023
description:
  "The Open Data Protocol (OData) for representing and interacting with structured
  content is comprised of a set of specifications. The core specification for the
  protocol is in OData Version 4.02 Part 1: Protocol.
  This document extends the core specification by defining representations for
  OData requests and responses using a JSON format."
