pagetitle: OData JSON Format Version 4.02
subtitle: Committee Specification Draft 01
filename: odata-json-format-v4.02-csd01
stage: csd01
previousStage: n/a
pubdate: 14 July 2023
pubdateISO: '2023-07-14'
copyright: © OASIS Open 2023
