name: Node CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Setup pandoc
        uses: nikeee/setup-pandoc@v1
        with:
          pandoc-version: 3.1.2
      - name: Build docs
        run: |
          npm ci
          npm run build --if-present
          git config user.name ${GITHUB_ACTOR}
          git config user.email ${PUSHER_EMAIL}
          git add docs/*/*.html docs/*/*.md docs/*/styles/*
          git diff-index --quiet HEAD docs/*/*.html docs/*/*.md docs/*/styles/* || (npm run pdf --if-present && git add docs/*/*.pdf && git commit -m "auto-refreshed")
          git push
        env:
          PUSHER_EMAIL: ${{ github.event.pusher.email }}
