name: Node CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: 3.8.3
      - name: Build docs
        run: |
          npm ci
          npm run build
          git config user.name ${GITHUB_ACTOR}
          git config user.email ${PUSHER_EMAIL}
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto-build (trigger nodejs.yml workflow)"
          git push
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
          PUSHER_EMAIL: ${{ github.event.pusher.email }}
