name: Node CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Setup pandoc
        uses: nikeee/setup-pandoc@v1
        with:
          pandoc-version: 3.1.2
      - run: npm ci
      - run: npm run build --if-present
      - run: git diff --exit-code docs
