name: Node CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: 3.8.3
      - name: Build docs
        run: |
          export PUPPETEER_SKIP_DOWNLOAD='true'
          npm ci
          npm run build
          git diff --exit-code docs
